---
title: "Multilingual analysis of topics in the Hartlib Papers"
output: html_document
author: Barbara McGillivray
---



```{r global_options, echo=FALSE}
#Global options:
knitr::opts_chunk$set(fig.width=7)
```

# Initialization

## Load libraries and data, and set initial parameters

Load libraries:

```{r message=FALSE}
op <- options(warn = (-1)) # suppress warnings 
#library(readtext)
#library(tidyverse)
library(reshape2)
library(pheatmap)
library("gplots")
options(op) # reset the default value
```

Directory and file names:

```{r}
path =  file.path("/Users", "bmcgillivray", "Documents", "OneDrive", "The Alan Turing Institute", "The Alan Turing Institute", "Hartlib Papers - Documents", "Topics", fsep = "/")
path_in = paste(path, "analysis", "output", sep = "/")
input_file_name1 = 'Topics_languages_dataframe.csv'
input_file_name2 = 'Topics_languages_letters_dataframe.csv'
```

# Number of subtopics by topic by language

Read input:

```{r}
df = read.csv(paste(path_in, input_file_name1, sep = "/"), sep = "\t", header = T)
head(df)
dim(df)
```

## Initial exploration

```{r}
summary(df)
summary(df$language)
summary(df$topic)
summary(df$number_subtopics)
hist(df$number_subtopics)
```

## Heatmap

```{r}
m = acast(df, language~topic, value.var="number_subtopics")
png(file = paste(path_in, "heatmap_topics_num-subtopics.png", sep = "/"))
heatmap(m)
dev.off()
```

# Number of letters by topic by language


Read input:

```{r}
dfl = read.csv(paste(path_in, input_file_name2, sep = "/"), sep = "\t", header = T)
head(dfl)
dim(dfl)
```

## Initial exploration

```{r}
summary(dfl)
summary(dfl$language)
summary(dfl$topic)
summary(dfl$number_letters)
hist(dfl$number_letters)
```

## Heatmap

```{r}
ml = acast(dfl, language~topic, value.var="number_letters")
ml[ is.na(ml) ] <- 0
png(file = paste(path_in, "heatmap_topics_num-letters.png", sep = "/"))
heatmap(ml)
dev.off()
```

Other heatmaps:

```{r}
png(file = paste(path_in, "heatmap2_topics_num-letters.png", sep = "/"))
heatmap.2(ml, scale = "none", col = bluered(100), trace = "none", density.info = "none")
dev.off()
png(file = paste(path_in, "heatmap3_topics_num-letters.png", sep = "/"))
pheatmap(ml, cutree_rows = 4)
dev.off()
```

